---
apiVersion: "v2"
name: "sonarr"
description: "A Sonarr Helm chart for Kubernetes. Warning This chart is currently in alpha and hasn't been tested yet."
type: "application"
version: "0.2.2"
# renovate: image=ghcr.io/linuxserver/sonarr
appVersion: "4.0.18.2971-ls315@sha256:916844aff737c06c12066be9146cc604c104cec66eb8e07e545cb3719a4b771a"
icon: "https://avatars.githubusercontent.com/u/1082903"
annotations:
  artifacthub.io/changes: |
    - kind: fixed
      description: Remove the digest from the version label
  artifacthub.io/links: |
    - name: Helm Repo
      url: https://github.com/panzer1119/helm-charts
  artifacthub.io/maintainers: |
    - name: Paul Hagedorn
      email: panzer1119@gmail.com
...
