---
apiVersion: "v2"
name: "sonarr"
description: "A Sonarr Helm chart for Kubernetes. Warning This chart is currently in alpha and hasn't been tested yet."
type: "application"
version: "0.2.2"
# renovate: image=ghcr.io/linuxserver/sonarr
appVersion: "4.0.16.2944-ls304@sha256:21c1c3d52248589bb064f5adafec18cad45812d7a01d317472955eef051e619b"
icon: "https://avatars.githubusercontent.com/u/1082903"
annotations:
  artifacthub.io/changes: |
    - kind: fixed
      description: Remove the digest from the version label
  artifacthub.io/links: |
    - name: Helm Repo
      url: https://github.com/panzer1119/helm-charts
  artifacthub.io/maintainers: |
    - name: Paul Hagedorn
      email: panzer1119@gmail.com
...
