---
apiVersion: "v2"
name: "radarr"
description: "A Radarr Helm chart for Kubernetes. Warning This chart is currently in alpha and hasn't been tested yet."
type: "application"
version: "0.2.2"
# renovate: image=ghcr.io/linuxserver/radarr
appVersion: "6.1.1.10360-ls303@sha256:079e48870584baf2a3e7e43e7ba6d3c834555931851a59c82c51cc792d285caf"
icon: "https://avatars.githubusercontent.com/u/25025331"
annotations:
  artifacthub.io/changes: |
    - kind: fixed
      description: Remove the digest from the version label
  artifacthub.io/links: |
    - name: Helm Repo
      url: https://github.com/panzer1119/helm-charts
  artifacthub.io/maintainers: |
    - name: Paul Hagedorn
      email: panzer1119@gmail.com
...
