---
apiVersion: "v2"
name: "radarr"
description: "A Radarr Helm chart for Kubernetes. Warning This chart is currently in alpha and hasn't been tested yet."
type: "application"
version: "0.2.2"
# renovate: image=ghcr.io/linuxserver/radarr
appVersion: "6.4.4.10685-ls319@sha256:7dfd049e79c00b16fbc29c3f5d96a9e7b9e73a23930b4c5b3c4541d60b366814"
icon: "https://avatars.githubusercontent.com/u/25025331"
annotations:
  artifacthub.io/changes: |
    - kind: fixed
      description: Remove the digest from the version label
  artifacthub.io/links: |
    - name: Helm Repo
      url: https://github.com/panzer1119/helm-charts
  artifacthub.io/maintainers: |
    - name: Paul Hagedorn
      email: panzer1119@gmail.com
...
