---
apiVersion: "v2"
name: "prowlarr"
description: "A Prowlarr Helm chart for Kubernetes. Warning This chart is currently in alpha and hasn't been tested yet."
type: "application"
version: "0.4.18"
# renovate: image=ghcr.io/linuxserver/prowlarr
appVersion: "2.4.0.5397-ls151@sha256:3950b5e48cf4ba9dab78fe14038dd7f062e66b7b4ab368b02c94a13f6a3dae9f"
icon: "https://raw.githubusercontent.com/Prowlarr/Prowlarr/refs/heads/develop/Logo/1024.png"
dependencies:
  - name: servarr-single
    version: 0.1.18
    repository: file://../servarr-single
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Bump servarr-single dependency to 0.1.18
  artifacthub.io/links: |
    - name: Helm Repo
      url: https://github.com/Panzer1119/helm-charts
  artifacthub.io/maintainers: |
    - name: Paul Hagedorn
      email: panzer1119@gmail.com
...
