---
apiVersion: "v2"
name: "prowlarr"
description: "A Prowlarr Helm chart for Kubernetes. Warning This chart is currently in alpha and hasn't been tested yet."
type: "application"
version: "0.4.15"
# renovate: image=ghcr.io/linuxserver/prowlarr
appVersion: "2.3.5.5327-ls148@sha256:2489c6dbaf11e3a6d71aeb2e6980d04193d4af611aa7064a974851222fd41722"
icon: "https://raw.githubusercontent.com/Prowlarr/Prowlarr/refs/heads/develop/Logo/1024.png"
dependencies:
  - name: servarr-single
    version: 0.1.15
    repository: file://../servarr-single
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Bump servarr-single dependency to 0.1.15
  artifacthub.io/links: |
    - name: Helm Repo
      url: https://github.com/Panzer1119/helm-charts
  artifacthub.io/maintainers: |
    - name: Paul Hagedorn
      email: panzer1119@gmail.com
...
